--This is a table we utilize in the OOF data processing 
--The table translates the CDB data codes into the CCD descriptions

-- Create the table
CREATE TABLE PAEC_CCD_CERT_CODES (
    code  VARCHAR(10) NOT NULL,
    label VARCHAR(255) NOT NULL
);


-- INSERT statements for PAEC_CCD_CERT_CODES (code, label)
INSERT INTO PAEC_CCD_CERT_CODES (code, label) VALUES
('198', 'HEAR IMPRD  6/PREK DISAB E'),
('209', 'LIC AS AUDIOLOGIST'),
('214', 'TEACHER CERT IN PE (PHYS ED @1 6)'),
('215', 'CERT IN HEALTH 6, HEALTH ED @4, FAM CON SC 1'),
('218', 'SLPA'),
('2313', 'SEE CURRICULUM FRAMEWORK FOR SPECIFIC CTE COVERAGE'),
('2800', 'IND ENGR'),
('2803', 'LAB TECH'),
('2804', 'GASENG RPR'),
('3046', 'OPER ENGR'),
('4004', 'TEC ELEC'),
('4010', 'LOG TECH'),
('4021', 'TEC CONSTR'),
('4039', 'TEC EN AID'),
('4040', 'HEALTH FIT SPEC'),
('4044', 'TEC OPTICS'),
('4051', 'TEC X RAY'),
('4058', 'JR ROTC'),
('4075', 'BUS DP'),
('4115', 'AC HEAT ME'),
('4143', 'WEB DEV'),
('4147', 'DENTL ASST'),
('4150', 'WSP OPER'),
('4310', 'AG SUPPLI'),
('4684', 'PH THERTEC'),
('580', 'IND ENGR'),
('615', 'ADVR PROM'),
('665', 'PH THERTEC'),
('693', 'OC THER AS'),
('713', 'ELECT DP'),
('746', 'ELEM ED K/PROF IN FRENCH'),
('747', 'ELEM ED K/PROF IN GERMAN'),
('748', 'ELEM ED K/PROF IN SPANISH'),
('750', 'IN ACCORDANCE WITH RULE 6A-1.0502,FAC'),
('751', 'ELEM ED @3/PROF IN FRENCH'),
('752', 'ELEM ED @3/PROF IN GERMAN'),
('753', 'ELEM ED @3/PROF IN SPANISH'),
('773', 'SEE SECTION 1 FOR SPECIFIC INFORMATION ON'),
('774', 'EXEMPTIONS TO THE ENDORSEMENT.'),
('776', 'RED CROSS WATER SAFETY INSTR (WSI) OR EQUIVALENT'),
('777', 'RED CROSS INSTRUCTOR'),
('799', 'CLASSICAL ED (RESTRICTED)'),
('817', 'ELEM ED @3/PROF IN ITALIAN'),
('818', 'ELEM ED K/PROF IN ITALIAN'),
('819', 'INTENSIVE READING INTERVENTIONS (TIER 3) MUST BE'),
('820', 'DELIVERED BY INSTRUCTIONAL PERSONNEL WHO POSSESS'),
('821', 'A LITERACY MICRO-CREDENTIAL OR ARE CERTIFIED OR'),
('822', 'ENDORSED IN READING. INSTRUCTIONAL PERSONNEL WHO'),
('823', 'POSSESS A LITERACY MICRO-CREDENTIAL AND ARE'),
('824', 'DELIVERING INTENSIVE READING INTERVENTIONS (TIER3)'),
('825', 'MUST BE SUPERVISED BY AN INDIVIDUAL CERTIFIED OR'),
('826', 'ENDORSED IN READING.'),
('850', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN LATIN'),
('854', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN ARABIC'),
('855', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN CHIN'),
('856', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN JAP'),
('861', 'ANY BUSINESS ED/TC COOP ED E G'),
('863', 'ANY HOME EC/TC COOP ED E G'),
('880', 'LIC SCH PSYCH'),
('890', 'RID'),
('891', 'CERT CPR INSTRUCTOR BY HEART ASSOC OR RED CROSS'),
('892', 'FRID'),
('893', 'LIC AS PTA'),
('894', 'LIC AS OTA'),
('895', 'REG AS SPEECH THER AIDE'),
('896', 'EX ED FIELD'),
('899', 'NA'),
('900', 'LIC AS OCCUP THER'),
('901', 'LIC SP LG PATH'),
('902', 'LIC AS PHY THER'),
('914', 'ANY FIELD WHEN CERT REFLECTS BACHELOR OR HIGHER'),
('919', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN CREOLE'),
('920', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN PORTUG'),
('921', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN CREEK'),
('930', 'LIC ATH TR'),
('931', 'ANY FIELD/LIC ATH TR'),
('938', 'FOR CDA OR CDA EQUIV, SEE SEC. 1:PREK BASIC DEF.'),
('939', 'INCLUSIVE SETTING, SEE SECTION 1, PREK EXCEPTIONAL'),
('940', 'VOLUNTARY PREK EDUCATION'),
('941', 'CDA OR CDA EQUIVALENT'),
('942', 'BACHELORS DEGREE OR HIGHER'),
('943', 'IN ANY OF THE FOLLOWING AREAS'),
('944', 'SEE SEC.1, PREK BASIC DEFINITION'),
('945', 'IN ELEMENTARY EDUCATION'),
('946', 'ASSOCIATES, OR HIGHER, DEGREE IN CHILD DEVELOPMENT'),
('947', 'ASSOCIATES OR HIGHER DEGREE IN AN UNRELATED FIELD'),
('948', 'EDUCATIONAL CREDENTIALS'),
('949', 'SEE SECTION 1.'),
('967', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN GREEK'),
('968', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN HEBREW'),
('969', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN ITAL'),
('970', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN RUS'),
('971', 'ANY FIELD CERT REFL BACHELOR OR HIG/PROF IN TUR'),
('975', 'ANY FIELD CERT REFL BACH OR HIG/PROF IN GUJARATI'),
('989', 'SEE CURRICULUM FRAMEWORK FOR SPECIFIC CTE COVERAGE'),
('993', 'REQUIRES DUAL CERTIFICATION IN PE & HEALTH:'),
('996', 'IF CONTRACTED, IN ACCORDANCE WITH 6A-6.0361, FAC'),
('9999', 'ANY FIELD');

INSERT INTO PAEC_CCD_CERT_CODES (code, label)
	SELECT 'E308' as code , 'Adaptive Physical Education Endorsement' as label UNION ALL
	SELECT '3114', 'Administration' UNION ALL
	SELECT '4114', 'Administration' UNION ALL
	SELECT '6114', 'Administration' UNION ALL
	SELECT '3001', 'Administration & Supervision' UNION ALL
	SELECT '4001', 'Administration & Supervision' UNION ALL
	SELECT '6001', 'Administration & Supervision' UNION ALL
	SELECT '2114', 'Administration of Adult Education' UNION ALL
	SELECT '1800', 'Agriculture' UNION ALL
	SELECT 'E981', 'American Sign Language Endorsement' UNION ALL
	SELECT '6300', 'Art' UNION ALL
	SELECT '3004', 'Art Education' UNION ALL
	SELECT 'E428', 'Athletic Coaching Endorsement' UNION ALL
	SELECT 'E304', 'Autism Spectrum Disorders Endorsement' UNION ALL
	SELECT '1052', 'Biology' UNION ALL
	SELECT '4009', 'Bookkeeping' UNION ALL
	SELECT '1006', 'Business Education' UNION ALL
	SELECT '1050', 'Chemistry' UNION ALL
	SELECT 'E851', 'Civics Seal of Excellence' UNION ALL
	SELECT '6313', 'Computer Science' UNION ALL
	SELECT '6328', 'Dance' UNION ALL
	SELECT '6903', 'Deaf or Hard of Hearing' UNION ALL
	SELECT '1150', 'Drama' UNION ALL
	SELECT 'E011', 'Driver Education' UNION ALL
	SELECT '0012', 'Early Childhood Education' UNION ALL
	SELECT '1310', 'Earth-Space Science' UNION ALL
	SELECT '1059', 'Economics' UNION ALL
	SELECT 'F399', 'Educational Leadership' UNION ALL
	SELECT 'D043', 'Educational Media Specialist' UNION ALL
	SELECT '3020', 'Elementary Education' UNION ALL
	SELECT 'K020', 'Elementary Education' UNION ALL
	SELECT '6301', 'Emotionally Handicapped' UNION ALL
	SELECT '1803', 'Engineering and Technology Education' UNION ALL
	SELECT '1021', 'English' UNION ALL
	SELECT '3021', 'English' UNION ALL
	SELECT '6172', 'English for Speakers of Other Languages' UNION ALL
	SELECT 'E172', 'English for Speakers of Other Languages Endorsement' UNION ALL
	SELECT '6048', 'Exceptional Student Education' UNION ALL
	SELECT '1730', 'Family & Consumer Science' UNION ALL
	SELECT '4035', 'French' UNION ALL
	SELECT '1061', 'Geography' UNION ALL
	SELECT '4038', 'German' UNION ALL
	SELECT 'E206', 'Gifted' UNION ALL
	SELECT '4030', 'Graphic Arts' UNION ALL
	SELECT '6311', 'Health' UNION ALL
	SELECT '4023', 'Health Education' UNION ALL
	SELECT '1057', 'History' UNION ALL
	SELECT '6132', 'Humanities' UNION ALL
	SELECT '6075', 'Instrumental Music' UNION ALL
	SELECT '4041', 'Italian' UNION ALL
	SELECT '1033', 'Journalism' UNION ALL
	SELECT '4037', 'Latin' UNION ALL
	SELECT '4108', 'Law' UNION ALL
	SELECT 'E852', 'Literacy Coach Endorsement' UNION ALL
	SELECT '1804', 'Marketing' UNION ALL
	SELECT '1044', 'Mathematics' UNION ALL
	SELECT '3044', 'Mathematics' UNION ALL
	SELECT '6303', 'Mentally Handicapped' UNION ALL
	SELECT 'C314', 'Middle Grades English' UNION ALL
	SELECT 'C316', 'Middle Grades General Science' UNION ALL
	SELECT 'C329', 'Middle Grades Integrated Curriculum' UNION ALL
	SELECT 'C315', 'Middle Grades Mathematics' UNION ALL
	SELECT '6307', 'Music' UNION ALL
	SELECT '3045', 'Music Education' UNION ALL
	SELECT 'E323', 'Orientation & Mobility Endorsement' UNION ALL
	SELECT '1046', 'Physical Education' UNION ALL
	SELECT '5046', 'Physical Education' UNION ALL
	SELECT '6046', 'Physical Education' UNION ALL
	SELECT '1051', 'Physics' UNION ALL
	SELECT '1058', 'Political Science' UNION ALL
	SELECT 'E324', 'Prekindergarten Disabilities Endorsement' UNION ALL
	SELECT 'H327', 'Prekindergarten/Primary Ed' UNION ALL
	SELECT 'L306', 'Preschool Education' UNION ALL
	SELECT 'B309', 'Primary Education' UNION ALL
	SELECT '1074', 'Psychology' UNION ALL
	SELECT '6146', 'Reading' UNION ALL
	SELECT 'E146', 'Reading (Endorsement)' UNION ALL
	SELECT '4121', 'Russian' UNION ALL
	SELECT 'D320', 'School (Guidance)Counseling' UNION ALL
	SELECT 'F398', 'School Principal' UNION ALL
	SELECT 'D322', 'School Psychologist' UNION ALL
	SELECT 'D321', 'School Social Worker' UNION ALL
	SELECT '3049', 'Science' UNION ALL
	SELECT '4049', 'Science' UNION ALL
	SELECT '1312', 'Social Science' UNION ALL
	SELECT 'C317', 'Social Science' UNION ALL
	SELECT '3056', 'Social Studies' UNION ALL
	SELECT '1060', 'Sociology' UNION ALL
	SELECT '4036', 'Spanish' UNION ALL
	SELECT '6202', 'Specific Learning Disabilities' UNION ALL
	SELECT '1062', 'Speech' UNION ALL
	SELECT '6018', 'Speech Correction' UNION ALL
	SELECT '6217', 'Speech Language Associate' UNION ALL
	SELECT '6319', 'Speech Language Impaired' UNION ALL
	SELECT '3113', 'Supervision' UNION ALL
	SELECT '4113', 'Supervision' UNION ALL
	SELECT '6113', 'Supervision' UNION ALL
	SELECT 'E805', 'Teacher Coordinator of Cooperative Education Endorsement' UNION ALL
	SELECT '6013', 'Varying Exceptionalities' UNION ALL
	SELECT '6305', 'Visually Impaired' UNION ALL
	SELECT '6147', 'Vocal Music' UNION ALL
	SELECT '6170', 'World Language - Arabic' UNION ALL
	SELECT '6143', 'World Language - Chinese' UNION ALL
	SELECT '6035', 'World Language - French' UNION ALL
	SELECT '6038', 'World Language - German' UNION ALL
	SELECT '6039', 'World Language - Greek' UNION ALL
	SELECT '6966', 'World Language - Haitian Creole' UNION ALL
	SELECT '6115', 'World Language - Hebrew' UNION ALL
	SELECT '6041', 'World Language - Italian' UNION ALL
	SELECT '6040', 'World Language - Japanese' UNION ALL
	SELECT '6037', 'World Language - Latin' UNION ALL
	SELECT '6042', 'World Language - Portuguese' UNION ALL
	SELECT '6121', 'World Language - Russian' UNION ALL
	SELECT '6036', 'World Language - Spanish' UNION ALL
	SELECT '6034', 'World Language - Turkish' UNION ALL
	SELECT '725', 'ANY EXCEPT ED FIELD' UNION ALL
	SELECT '865', 'ANY AG ED' UNION ALL
	SELECT '881', 'ANY BUSINESS ED' UNION ALL
	SELECT '883', 'ANY HEALTH OCCUP' UNION ALL
	SELECT '889', 'ANY PUB SERV OCC ED' UNION ALL
	SELECT '897', 'ANY MARKETING ED' UNION ALL
	SELECT '907', 'ANY HOME ECONOMICS ED' UNION ALL
	SELECT '914', 'ANY FIELD WHEN CERT REFLECTS BACHELOR OR HIGHER' UNION ALL
	SELECT '916', 'ANY WORLD LANGUAGE' UNION ALL
	SELECT '917', 'FOREIGN LANGUAGE/ESOL E	' UNION ALL
	SELECT '964', 'ANY ACADEMIC COVERAG' UNION ALL
	SELECT '991', 'ANY VOCATIONAL FIELD OR COVERAGE' UNION ALL
	SELECT '999', 'ANY FIELD'  UNION ALL
	
	
	
	SELECT '002', 'ESE 6/ELEM ED K' UNION ALL
	SELECT '008', 'ESE 6/ELEM ED @3' UNION ALL
	SELECT '015', 'ESE 6/PK PRIMARY H' UNION ALL
	SELECT '016', 'ESE 6/PRIMARY ED @B' UNION ALL
	SELECT '017', 'ESE 6/E CHILD ED !0' UNION ALL
	SELECT '019', 'ESE 6/ENGLISH @3' UNION ALL
	SELECT '025', 'ENGLISH 1/READ E' UNION ALL
	SELECT '027', 'ENGLISH 1/READ E/MG SOC SCI C' UNION ALL
	SELECT '032', 'MG ENG C/READ E/MG SOC SCI C' UNION ALL
	SELECT '047', 'ESOL 6/READ E/MG SOC SCI C' UNION ALL
	SELECT '053', 'READING 6/MG SOC SCI C' UNION ALL
	SELECT '054', 'ENGLISH 1/READ E/SOCIAL SCI 1' UNION ALL
	SELECT '064', 'MG ENG C/READ E/SOCIAL SCI 1' UNION ALL
	SELECT '065', 'ESOL E/READ E/SOCIAL SCI 1' UNION ALL
	SELECT '066', 'READING 6/SOCIAL SCI 1' UNION ALL
	SELECT '067', 'MNTL HNDCP @6/ELEM ED K' UNION ALL
	SELECT '068', 'MNTL HNDCP @6/ELEM ED @3' UNION ALL
	SELECT '069', 'MNTL HNDCP @6/PK PRIMARY H' UNION ALL
	SELECT '072', 'MNTL HNDCP @6/PRIMARY ED @B' UNION ALL
	SELECT '073', 'MNTL HNDCP @6/E CHILD ED !0' UNION ALL
	SELECT '076', 'MNTL HNDCP @6/ENGLISH @3' UNION ALL
	SELECT '077', 'VARYING EX @6/ELEM ED K' UNION ALL
	SELECT '080', 'VARYING EX @6/ELEM ED @3' UNION ALL
	SELECT '081', 'VARYING EX @6/PK PRIMARY H' UNION ALL
	SELECT '082', 'VARYING EX @6/PRIMARY ED @B' UNION ALL
	SELECT '084', 'VARYING EX @6/E CHILD ED !0' UNION ALL
	SELECT '085', 'VARYING EX @6/ENGLISH @3' UNION ALL
	SELECT '088', 'EMTL HNDCP @6/ELEM ED K' UNION ALL
	SELECT '089', 'EMTL HNDCP @6/ELEM ED @3' UNION ALL
	SELECT '090', 'EMTL HNDCP @6/PK PRIMARY H' UNION ALL
	SELECT '091', 'EMTL HNDCP @6/PRIMARY ED @B' UNION ALL
	SELECT '092', 'EMTL HNDCP @6/E CHILD ED !0' UNION ALL
	SELECT '093', 'EMTL HNDCP @6/ENGLISH @3' UNION ALL
	SELECT '095', 'SPC LRN DS @6/ELEM ED K' UNION ALL
	SELECT '097', 'SPC LRN DS @6/ELEM ED @3' UNION ALL
	SELECT '098', 'SPC LRN DS @6/PK PRIMARY H' UNION ALL
	SELECT '100', 'SPC LRN DS @6/PRIMARY ED @B' UNION ALL
	SELECT '101', 'SPC LRN DS @6/E CHILD ED !0' UNION ALL
	SELECT '103', 'SPC LRN DS @6/ENGLISH @3' UNION ALL
	SELECT '104', 'ESE 6/MATH @3' UNION ALL
	SELECT '106', 'MNTL HNDCP @6/MATH @3' UNION ALL
	SELECT '107', 'VARYING EX @6/MATH @3' UNION ALL
	SELECT '109', 'EMTL HNDCP @6/MATH @3' UNION ALL
	SELECT '110', 'SPC LRN DS @6/MATH @3' UNION ALL
	SELECT '111', 'ESE 6/SCIENCE @3' UNION ALL
	SELECT '116', 'MNTL HNDCP @6/SCIENCE @3' UNION ALL
	SELECT '117', 'VARYING EX @6/SCIENCE @3' UNION ALL
	SELECT '118', 'EMTL HNDCP @6/SCIENCE @3' UNION ALL
	SELECT '119', 'SPC LRN DS @6/SCIENCE @3' UNION ALL
	SELECT '120', 'ESE 6/MG GEN SCI C' UNION ALL
	SELECT '122', 'MNTL HNDCP @6/MG GEN SCI C' UNION ALL
	SELECT '123', 'VARYING EX @6/MG GEN SCI C' UNION ALL
	SELECT '124', 'EMTL HNDCP @6/MG GEN SCI C' UNION ALL
	SELECT '125', 'SPC LRN DS @6/MG GEN SCI C' UNION ALL
	SELECT '126', 'ESE 6/SOC ST @3' UNION ALL
	SELECT '127', 'MNTL HNDCP @6/SOC ST @3' UNION ALL
	SELECT '128', 'VARYING EX@6/ENGLISH 1' UNION ALL
	SELECT '129', 'EMTL HNDCP @6/SOC ST @3' UNION ALL
	SELECT '130', 'SPC LRN DS @6/SOC ST @3' UNION ALL
	SELECT '131', 'ESE 6/MG SOC SCI C' UNION ALL
	SELECT '133', 'MNTL HNDCP @6/MG SOC SCI C' UNION ALL
	SELECT '134', 'VARYING EX @6/MG SOC SCI C' UNION ALL
	SELECT '136', 'EMTL HNDCP @6/MG SOC SCI C' UNION ALL
	SELECT '137', 'SPC LRN DS @6/MG SOC SCI C' UNION ALL
	SELECT '139', 'ESE 6/ENGLISH 1' UNION ALL
	SELECT '140', 'ESE 6/MGIC ?C' UNION ALL
	SELECT '141', 'ESE 6/MG ENG C' UNION ALL
	SELECT '142', 'MNTL HNDCP @6/ENGLISH 1' UNION ALL
	SELECT '144', 'MNTL HNDCP @6/MGIC ?C' UNION ALL
	SELECT '149', 'MNTL HNDCP @6/MG ENG C' UNION ALL
	SELECT '151', 'VARYING EX @6/ENGLISH 1' UNION ALL
	SELECT '152', 'VARYING EX @6/MGIC ?C' UNION ALL
	SELECT '155', 'VARYING EX @6/MG ENG C' UNION ALL
	SELECT '156', 'EMTL HNDCP @6/ENGLISH 1' UNION ALL
	SELECT '157', 'EMTL HNDCP @6/MGIC ?C' UNION ALL
	SELECT '158', 'EMTL HNDCP @6/MG ENG C' UNION ALL
	SELECT '159', 'SPC LRN DS @6/ENGLISH 1' UNION ALL
	SELECT '160', 'SPC LRN DS @6/MGIC ?C' UNION ALL
	SELECT '161', 'SPC LRN DS @6/MG ENG C' UNION ALL
	SELECT '162', 'ESE 6/MATH 1' UNION ALL
	SELECT '163', 'ESE 6/MGIC ?C' UNION ALL
	SELECT '164', 'ESE 6/MG MATH C' UNION ALL
	SELECT '165', 'MNTL HNDCP @6/MATH 1' UNION ALL
	SELECT '166', 'MNTL HNDCP @6/HEALTH 6' UNION ALL
	SELECT '167', 'MNTL HNDCP @6/MG MATH C' UNION ALL
	SELECT '168', 'VARYING EX @6/MATH 1' UNION ALL
	SELECT '169', 'VARYING EX @6/HEALTH 6' UNION ALL
	SELECT '173', 'VARYING EX @6/MG MATH C' UNION ALL
	SELECT '180', 'EMTL HNDCP @6/MATH 1' UNION ALL
	SELECT '181', 'PHYS ED 6 + HEALTH ED @4' UNION ALL
	SELECT '182', 'PHYS ED 6 + FAM CONS SC 1' UNION ALL
	SELECT '183', 'PHYS ED @1 + HEALTH ED @4' UNION ALL
	SELECT '184', 'PHYS ED @1 + FAM CON SC 1' UNION ALL
	SELECT '188', 'PHYS ED 6 + HEALTH 6' UNION ALL
	SELECT '189', 'PHYS ED @1 + HEALTH 6' UNION ALL
	SELECT '190', 'ESE 6/PREK DISAB E' UNION ALL
	SELECT '191', 'EMTL HNDCP @6/PREK DISAB E' UNION ALL
	SELECT '192', 'MNTL HNDCP @6/PREK DISAB E' UNION ALL
	SELECT '193', 'SPC LRN DS @6/PREK DISAB E' UNION ALL
	SELECT '194', 'SPCH CORR @6/PREK DISAB E' UNION ALL
	SELECT '195', 'SP LG IMPR  6/PREK DISAB E' UNION ALL
	SELECT '196', 'VARYING EX @6/PREK DISAB E' UNION ALL
	SELECT '199', 'VISU IMPRD  6/PREK DISAB E' UNION ALL
	SELECT '200', 'EMTL HNDCP @6/HEALTH 6' UNION ALL
	SELECT '201', 'EMTL HNDCP @6/MG MATH C' UNION ALL
	SELECT '203', 'SPC LRN DS @6/MATH 1' UNION ALL
	SELECT '207', 'SPC LRN DS @6/HEALTH 6' UNION ALL
	SELECT '208', 'SPC LRN DS @6/MG MATH C' UNION ALL
	SELECT '210', 'ESE 6/MATH @4' UNION ALL
	SELECT '211', 'MNTL HNDCP @6/MATH @4' UNION ALL
	SELECT '212', 'VARYING EX @6/MATH @4' UNION ALL
	SELECT '213', 'EMTL HNDCP @6/MATH @4' UNION ALL
	SELECT '216', 'SPC LRN DS @6/MATH @4' UNION ALL
	SELECT '219', 'ESE 6/SCIENCE @4' UNION ALL
	SELECT '220', 'MNTL HNDCP @6/SCIENCE @4' UNION ALL
	SELECT '221', 'VARYING EX @6/SCIENCE @4' UNION ALL
	SELECT '222', 'EMTL HNDCP @6/SCIENCE @4' UNION ALL
	SELECT '223', 'SPC LRN DS @6/SCIENCE @4' UNION ALL
	SELECT '224', 'ESE 6/CHEM 1' UNION ALL
	SELECT '225', 'MNTL HNDCP @6/CHEM 1' UNION ALL
	SELECT '226', 'VARYING EX @6/CHEM 1' UNION ALL
	SELECT '227', 'EMTL HNDCP @6/CHEM 1' UNION ALL
	SELECT '228', 'SPC LRN DS @6/CHEM 1' UNION ALL
	SELECT '229', 'ESE 6/BIOLOGY 1' UNION ALL
	SELECT '230', 'MNTL HNDCP @6/BIOLOGY 1' UNION ALL
	SELECT '231', 'VARYING EX @6/BIOLOGY 1' UNION ALL
	SELECT '232', 'EMTL HNDCP @6/BIOLOGY 1' UNION ALL
	SELECT '233', 'SPC LRN DS @6/BIOLOGY 1' UNION ALL
	SELECT '234', 'ESE 6/PHYSICS 1' UNION ALL
	SELECT '235', 'MNTL HNDCP @6/PHYSICS 1' UNION ALL
	SELECT '236', 'VARYING EX @6/PHYSICS 1' UNION ALL
	SELECT '237', 'EMTL HNDCP @6/PHYSICS 1' UNION ALL
	SELECT '238', 'SPC LRN DS @6/PHYSICS 1' UNION ALL
	SELECT '239', 'ESE 6/ERTH-SPA S 1' UNION ALL
	SELECT '240', 'MNTL HNDCP @6/ERTH-SPA S 1' UNION ALL
	SELECT '241', 'VARYING EX @6/ERTH-SPA S 1' UNION ALL
	SELECT '242', 'EMTL HNDCP @6/ERTH-SPA S 1' UNION ALL
	SELECT '243', 'SPC LRN DS @6/ERTH-SPA S 1' UNION ALL
	SELECT '244', 'ESE 6/SOCIAL SCI 1' UNION ALL
	SELECT '245', 'MNTL HNDCP @6/SOCIAL SCI 1' UNION ALL
	SELECT '246', 'VARYING EX@6/SOCIAL SCI 1' UNION ALL
	SELECT '247', 'EMTL HNDCP @6/SOCIAL SCI 1' UNION ALL
	SELECT '248', 'SPC LRN DS @6/SOCIAL SCI 1' UNION ALL
	SELECT '249', 'ESE 6/POL SCI @1' UNION ALL
	SELECT '250', 'MNTL HNDCP @6/POL SCI @1' UNION ALL
	SELECT '251', 'VARYING EX @6/POLSCI @1' UNION ALL
	SELECT '252', 'EMTL HNDCP @6/POL SCI @1' UNION ALL
	SELECT '253', 'SPC LRN DS @6/POL SCI @1' UNION ALL
	SELECT '254', 'ESE 6/HISTORY @1' UNION ALL
	SELECT '255', 'MNTL HNDCP @6/HISTORY @1' UNION ALL
	SELECT '256', 'VARYING EX @6/HISTORY @1' UNION ALL
	SELECT '257', 'EMTL HNDCP @6/HISTORY @1' UNION ALL
	SELECT '258', 'SPC LRN DS @6/HISTORY @1' UNION ALL
	SELECT '259', 'ESE 6/HEALTH ED @4' UNION ALL
	SELECT '260', 'MNTL HNDCP @6/HEALTH ED @4' UNION ALL
	SELECT '261', 'VARYING EX @6/HEALTH ED @4' UNION ALL
	SELECT '262', 'EMTL HNDCP @6/HEALTH ED @4' UNION ALL
	SELECT '263', 'SPC LRN DS @6/HEALTH ED @4' UNION ALL
	SELECT '264', 'ESE 6/ECONOMICS @1' UNION ALL
	SELECT '265', 'MNTL HNDCP @6/ECONOMICS @1' UNION ALL
	SELECT '266', 'VARYING EX @6/ECONOMICS @1' UNION ALL
	SELECT '267', 'EMTL HNDCP @6/ECONOMICS @1' UNION ALL
	SELECT '268', 'SPC LRN DS @6/ECONOMICS @1' UNION ALL
	SELECT '269', 'ESE 6/ART ED @4' UNION ALL
	SELECT '270', 'ESE 6/ART 6' UNION ALL
	SELECT '271', 'ESE 6/MUSIC 6' UNION ALL
	SELECT '272', 'ESE 6/DRAMA 1' UNION ALL
	SELECT '273', 'ESE 6/DRAMA @4' UNION ALL
	SELECT '274', 'MNTL HNDCP @6/ART ED @4' UNION ALL
	SELECT '275', 'MNTL HNDCP @6/ART 6' UNION ALL
	SELECT '276', 'MNTL HNDCP @6/MUSIC 6' UNION ALL
	SELECT '277', 'MNTL HNDCP @6/DRAMA 1' UNION ALL
	SELECT '278', 'MNTL HNDCP @6/DRAMA @4' UNION ALL
	SELECT '279', 'VARYING EX @6/ART ED @4' UNION ALL
	SELECT '280', 'VARYING EX @6/ART 6' UNION ALL
	SELECT '281', 'VARYING EX @6/MUSIC 6' UNION ALL
	SELECT '282', 'VARYING EX @6/DRAMA 1' UNION ALL
	SELECT '283', 'VARYING EX @6/DRAMA @4' UNION ALL
	SELECT '284', 'EMTL HNDCP @6/ART ED @4' UNION ALL
	SELECT '285', 'EMTL HNDCP @6/ART 6' UNION ALL
	SELECT '286', 'EMTL HNDCP @6/MUSIC 6' UNION ALL
	SELECT '287', 'EMTL HNDCP @6/DRAMA 1' UNION ALL
	SELECT '288', 'EMTL HNDCP @6/DRAMA @4' UNION ALL
	SELECT '289', 'SPC LRN DS @6/ART ED @4' UNION ALL
	SELECT '290', 'SPC LRN DS @6/ART 6' UNION ALL
	SELECT '291', 'SPC LRN DS @6/MUSIC 6' UNION ALL
	SELECT '292', 'SPC LRN DS @6/DRAMA 1' UNION ALL
	SELECT '293', 'SPC LRN DS @6/DRAMA @4' UNION ALL
	SELECT '294', 'ESE 6/PHYS ED 1' UNION ALL
	SELECT '295', 'ESE 6/PHYS ED 6' UNION ALL
	SELECT '296', 'ESE 6/@ADAPT PE E' UNION ALL
	SELECT '297', 'MNTL HNDCP @6/PHYS ED 1' UNION ALL
	SELECT '298', 'MNTL HNDCP @6/PHYS ED 6' UNION ALL
	SELECT '299', 'MNTL HNDCP @6/@ADAPT PE E' UNION ALL
	SELECT '318', 'VARYING EX @6/PHYS ED 1' UNION ALL
	SELECT '323', 'VARYING EX @6/PHYS ED 6' UNION ALL
	SELECT '330', 'MG ENG/READ E' UNION ALL
	SELECT '331', 'MGIC ?C/ESOL E' UNION ALL
	SELECT '332', 'VARYING EX @6/@ADAPT PE E' UNION ALL
	SELECT '333', 'EMTL HNDCP @6/PHYS ED 1' UNION ALL
	SELECT '334', 'EMTL HNDCP @6/PHYS ED 6' UNION ALL
	SELECT '335', 'EMTL HNDCP @6/@ADAPT PE E' UNION ALL
	SELECT '336', 'SPC LRN DS @6/PHYS ED 1' UNION ALL
	SELECT '337', 'SPC LRN DS @6/PHYS ED 6' UNION ALL
	SELECT '338', 'SPC LRN DS @6/@ADAPT PE E' UNION ALL
	SELECT '339', 'ESE 6/PHYS ED @5' UNION ALL
	SELECT '341', 'MNTL HNDCP @6/PHYS ED @5' UNION ALL
	SELECT '342', 'VARYING EX @6/PHYS ED @5' UNION ALL
	SELECT '343', 'EMTL HNDCP @6/PHYS ED @5' UNION ALL
	SELECT '344', 'SPC LRN DS @6/PHYS ED @5' UNION ALL
	SELECT '345', 'SPCH CORR @6/PHYS ED 1' UNION ALL
	SELECT '346', 'SPCH CORR @6/PHYS ED @5' UNION ALL
	SELECT '347', 'SPCH CORR @6/PHYS ED 6' UNION ALL
	SELECT '351', 'SP LG ASSOC 6/PHYS ED 1' UNION ALL
	SELECT '352', 'SP LG ASSOC 6/PHYS ED @5' UNION ALL
	SELECT '353', 'SP LG ASSOC 6/PHYS ED 6' UNION ALL
	SELECT '357', 'VISU IMPRD 6/PHYS ED 1' UNION ALL
	SELECT '358', 'VISU IMPRD 6/PHYS ED @5' UNION ALL
	SELECT '359', 'VISU IMPRD 6/PHYS ED 6' UNION ALL
	SELECT '360', 'SP LG IMPR 6/PHYS ED 1' UNION ALL
	SELECT '361', 'SP LG IMPR 6/PHYS ED @5' UNION ALL
	SELECT '362', 'SP LG IMPR 6/PHYS ED 6' UNION ALL
	SELECT '363', 'SPCH CORR 6/@ADAPT PE E' UNION ALL
	SELECT '365', 'SP LG ASSOC 6/@ADAPT PE E' UNION ALL
	SELECT '367', 'VISU IMPRD 6/@ADAPT PE E' UNION ALL
	SELECT '368', 'SP LG IMPR 6/@ADAPT PE E' UNION ALL
	SELECT '369', 'ESE 6/HEALTH 6' UNION ALL
	SELECT '371', 'ESE 6/PHYS ED 6' UNION ALL
	SELECT '372', 'MNTL HNDCP @6/PHYS ED 6' UNION ALL
	SELECT '373', 'VARYING EX @6/PHYS ED 6' UNION ALL
	SELECT '374', 'READ 6/ESOL 6' UNION ALL
	SELECT '375', 'BIOLOGY 1/BIOTECH 7' UNION ALL
	SELECT '376', 'BIOLOGY 1/BIOTECH G' UNION ALL
	SELECT '377', 'CHEMISTRY 1/BIOTECH 7' UNION ALL
	SELECT '378', 'CHEMISTRY 1/BIOTECH G' UNION ALL
	SELECT '450', 'ESE 6/SCHOOL PSYCH D' UNION ALL
	SELECT '451', 'MNTL HNDCP @6/SCHOOL PSYCH D' UNION ALL
	SELECT '452', 'VARYING EX @6/SCHOOL PSYCH D' UNION ALL
	SELECT '453', 'EMTL HNDCP @6/SCHOOL PSYCH D' UNION ALL
	SELECT '454', 'SPC LRN DS @6/SCHOOL PSYCH D' UNION ALL
	SELECT '455', 'ESE 6/GUID COUN D' UNION ALL
	SELECT '456', 'MNTL HNDCP @6/GUID COUN D' UNION ALL
	SELECT '457', 'VARYING EX @6/GUID COUN D' UNION ALL
	SELECT '458', 'EMTL HNDCP @6/GUID COUN D' UNION ALL
	SELECT '459', 'SPC LRN DS @6/GUID COUN D' UNION ALL
	SELECT '460', 'ELEM ED @3/READ E' UNION ALL
	SELECT '461', 'ENGLISH @3/READ E' UNION ALL
	SELECT '462', 'PK PRIMARY H/READ E' UNION ALL
	SELECT '463', 'ELEM ED K/READ E' UNION ALL
	SELECT '464', 'PRIMARY ED @B/READ E' UNION ALL
	SELECT '611', 'MG ENG C/ESOL E/READING E' UNION ALL
	SELECT '614', 'MGIC ?C/ESOL E/READ E' UNION ALL
	SELECT '723', 'E CHILD ED !0/PREK DISAB E' UNION ALL
	SELECT '724', 'PRIMARY ED@B/PREK DISAB E' UNION ALL
	SELECT '744', 'ELEM ED K/ESOL E' UNION ALL
	SELECT '756', 'PRIMARY ED B/ESOL E' UNION ALL
	SELECT '757', 'PK PRIMARY H/ESOL E' UNION ALL
	SELECT '758', 'ELEM ED @ 3/ESOL E' UNION ALL
	SELECT '759', 'MG ENG C/ESOL E' UNION ALL
	SELECT '768', 'ENGLISH @3/ESOL E' UNION ALL
	SELECT '784', 'ENGLISH 1/ESOL E' UNION ALL
	SELECT '813', 'ESOL 6/READING E' UNION ALL
	SELECT '814', 'ENGLISH 1/ESOL E/READING E' UNION ALL
	SELECT '815', 'READING 6/ESOL E' UNION ALL
	SELECT '860', 'ELEMENTARY (K-6) K/PREK DISAB E' UNION ALL
	SELECT '876', 'READING E/ANY FLD WHEN CERT REFLECTS BACHLR OR HGH' UNION ALL
	SELECT '904', 'DEAF HARD HEAR 6/PREK DISAB E' UNION ALL
	SELECT '917', 'WORLD LANGUAGE/ESOL E' UNION ALL
	SELECT '918', 'WORLD LANGUAGE/ESOL E/READ E' UNION ALL
	SELECT '954', 'PHYS ED@5/@ADAPT PE E' UNION ALL
	SELECT '955', 'VISU IMPRD 6/ORIEN MOBL E' UNION ALL
	SELECT '958', 'PHYS ED 1/@ADAPT PE E';
